[package]
name = "weechat"
version = "0.1.0"
authors = ["KokaKiwi <kokakiwi@kokakiwi.net>"]
description = "Weechat plugins API bindings for Rust"
license = "MIT"

[dependencies]
error-chain = "0.7"
libc = "0.2"
log = "0.3"
